# Generated by Django 4.2.27 on 2025-12-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violator_name', models.CharField(default='Unknown', max_length=100)),
                ('violation_type', models.CharField(choices=[('Person', 'Person'), ('Car', 'Car'), ('Bike', 'Bike'), ('Bus', 'Bus'), ('Truck', 'Truck'), ('Motorcycle', 'Motorcycle'), ('Unknown', 'Unknown')], default='Person', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.CharField(max_length=255)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
