# Generated by Django 4.2.27 on 2025-12-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_zone_x_percent', models.FloatField(default=0.6)),
                ('roi_x', models.IntegerField(default=0)),
                ('roi_y', models.IntegerField(default=0)),
                ('roi_w', models.IntegerField(default=100)),
                ('roi_h', models.IntegerField(default=100)),
            ],
        ),
    ]
